import 'dart:typed_data';
import 'package:awing_ai_learning/services/asset_pack_service.dart';

/// Service for loading vocabulary illustration images from the asset pack.
///
/// Images are generated by scripts/generate_images.py and stored in the
/// install-time asset pack at images/vocabulary/{key}.png where key is the
/// ASCII-safe version of the Awing word.
class ImageService {
  static final ImageService _instance = ImageService._();
  factory ImageService() => _instance;
  ImageService._();

  final AssetPackService _assetPack = AssetPackService();

  /// Cache of loaded image bytes.
  final Map<String, Uint8List?> _bytesCache = {};

  /// Maximum chars of the english slug appended to image filenames.
  /// MUST match `ENGLISH_SLUG_MAX` in scripts/generate_images.py.
  static const int _englishSlugMax = 32;

  /// AUDIO namespace key — one clip per Awing spelling regardless of English
  /// gloss. Used by PronunciationService for MP3 lookups.
  ///
  /// For image lookups, use `imageKey(awing, english)` instead — that key
  /// appends a slug of the english gloss so homonyms ("té" learn vs "té" sit)
  /// and tone-pair collisions each resolve to their own illustration.
  static String audioKey(String awingWord) {
    String key = awingWord.toLowerCase();

    // Strip tone diacritics
    key = key
        .replaceAll('á', 'a').replaceAll('à', 'a')
        .replaceAll('â', 'a').replaceAll('ǎ', 'a')
        .replaceAll('é', 'e').replaceAll('è', 'e')
        .replaceAll('ê', 'e').replaceAll('ě', 'e')
        .replaceAll('í', 'i').replaceAll('ì', 'i')
        .replaceAll('î', 'i').replaceAll('ǐ', 'i')
        .replaceAll('ó', 'o').replaceAll('ò', 'o')
        .replaceAll('ô', 'o').replaceAll('ǒ', 'o')
        .replaceAll('ú', 'u').replaceAll('ù', 'u')
        .replaceAll('û', 'u').replaceAll('ǔ', 'u');

    // Replace special vowels with ASCII
    key = key
        .replaceAll('ɛ́', 'e').replaceAll('ɛ̂', 'e').replaceAll('ɛ̌', 'e').replaceAll('ɛ', 'e')
        .replaceAll('ə́', 'e').replaceAll('ə̂', 'e').replaceAll('ə̌', 'e').replaceAll('ə', 'e')
        .replaceAll('ɔ́', 'o').replaceAll('ɔ̂', 'o').replaceAll('ɔ̌', 'o').replaceAll('ɔ', 'o')
        .replaceAll('ɨ́', 'i').replaceAll('ɨ̂', 'i').replaceAll('ɨ̌', 'i').replaceAll('ɨ', 'i')
        .replaceAll('ŋ', 'ng');

    // Remove glottal stops and special characters
    key = key.replaceAll("'", '').replaceAll("\u2019", '').replaceAll("\u2018", '');

    // Remove any remaining non-ASCII characters
    key = key.replaceAll(RegExp(r'[^a-z0-9]'), '');

    return key;
  }

  /// Slugify an English gloss for use as a filename suffix.
  /// MUST match `english_slug()` in scripts/generate_images.py exactly —
  /// the generator and the app are coupled through this filename format.
  ///
  /// Algorithm: lowercase → strip combining diacritics via NFD → map any
  /// non-[a-z0-9] run to a single underscore → trim edge underscores →
  /// truncate to `_englishSlugMax`. If the gloss is pure punctuation
  /// (slug would be empty), fall back to an MD5-hash prefix so the
  /// filename is still deterministic and unique.
  static String _englishSlug(String english) {
    String s = english.toLowerCase();

    // NFD normalize + strip combining marks (Unicode category Mn).
    // Dart's String doesn't expose Unicode categories directly, so we
    // enumerate the combining marks we actually see in our data (tone
    // diacritics + a safety net via a range check below).
    const combining = [
      '\u0300', '\u0301', '\u0302', '\u0303', '\u0304', '\u0306',
      '\u0307', '\u0308', '\u030a', '\u030b', '\u030c', '\u030f',
      '\u0323', '\u0324', '\u0327', '\u0328',
    ];
    for (final c in combining) {
      s = s.replaceAll(c, '');
    }
    // Belt-and-braces: drop any remaining chars in the U+0300..U+036F
    // combining-mark block.
    final buf = StringBuffer();
    for (final r in s.runes) {
      if (r >= 0x0300 && r <= 0x036F) continue;
      buf.writeCharCode(r);
    }
    s = buf.toString();

    // Anything non-alphanumeric → underscore, collapse runs.
    s = s.replaceAll(RegExp(r'[^a-z0-9]+'), '_');
    // Trim edge underscores.
    s = s.replaceAll(RegExp(r'^_+|_+$'), '');

    if (s.isEmpty) {
      // Pathological: english was all punctuation. Use a stable short hash
      // of the original input. Python uses md5; Dart's `hash` is different
      // so we use the same algorithm intent (first 8 hex chars) but with a
      // simple string hash fallback — the generator should have named the
      // file; the app just needs SOMETHING to look up.
      final code = english.hashCode.abs().toRadixString(16).padLeft(8, '0');
      return code.substring(0, 8);
    }
    if (s.length > _englishSlugMax) {
      s = s.substring(0, _englishSlugMax);
      // Strip trailing underscores created by the truncation boundary.
      s = s.replaceAll(RegExp(r'_+$'), '');
    }
    return s;
  }

  /// Image asset key for one (awing, english) pair. Matches the base
  /// filename written by `image_key()` in scripts/generate_images.py.
  ///
  /// NOTE on duplicates: When the Dart source has two identical
  /// (awing, english) literals, the generator writes `{base}.png`,
  /// `{base}__2.png`, `{base}__3.png`, etc. — but this method always
  /// returns the base key, so the app displays the first-occurrence
  /// illustration for every duplicate. See generate_images.py
  /// parse_vocabulary() docstring for the rationale.
  static String imageKey(String awingWord, String english) {
    return '${audioKey(awingWord)}__${_englishSlug(english)}';
  }

  /// Get the asset pack path for a vocabulary image (no "assets/" prefix).
  static String packPath(String awingWord, String english) {
    return 'images/vocabulary/${imageKey(awingWord, english)}.png';
  }

  /// Filename-length cap for multi-word keys (matches scripts/generate_images.py
  /// MULTI_WORD_KEY_MAX = 60). Must stay in sync with the Python side.
  static const int _multiWordKeyMax = 60;

  static String _truncate(String key) =>
      key.length > _multiWordKeyMax ? key.substring(0, _multiWordKeyMax) : key;

  /// Image key for an AwingPhrase (greeting, daily, classroom...).
  /// Mirrors `_multi_word_key("phrase", awing)` in generate_images.py.
  ///
  /// These namespaces use the 1-arg audio key (no english gloss suffix)
  /// because each phrase/sentence/story has exactly one canonical text
  /// and doesn't collide with homonyms the way vocabulary words do.
  static String phraseImageKey(String awingPhrase) =>
      'phrase_${_truncate(audioKey(awingPhrase))}';

  /// Image key for an AwingSentence (sentence-building, medium lessons).
  /// Mirrors `_multi_word_key("sentence", awing)` in generate_images.py.
  static String sentenceImageKey(String awingSentence) =>
      'sentence_${_truncate(audioKey(awingSentence))}';

  /// Image key for a StorySentence (stories mode).
  /// Mirrors `_multi_word_key("story", awing)` in generate_images.py.
  static String storyImageKey(String awingSentence) =>
      'story_${_truncate(audioKey(awingSentence))}';

  /// Asset pack paths for the 3 new namespaces.
  static String phrasePackPath(String awingPhrase) =>
      'images/vocabulary/${phraseImageKey(awingPhrase)}.png';

  static String sentencePackPath(String awingSentence) =>
      'images/vocabulary/${sentenceImageKey(awingSentence)}.png';

  static String storyPackPath(String awingSentence) =>
      'images/vocabulary/${storyImageKey(awingSentence)}.png';

  /// Load image bytes from the asset pack. Returns null if not found.
  /// Results are cached for performance.
  ///
  /// Pass the English gloss alongside the Awing word so homonyms resolve
  /// to their own illustrations. Callers that genuinely have no gloss
  /// (legacy code paths) can pass an empty string; the lookup will
  /// degrade to a hash-based slug but WILL MISS the generator-named file.
  Future<Uint8List?> getImageBytes(String awingWord, String english) async {
    final key = imageKey(awingWord, english);
    if (_bytesCache.containsKey(key)) return _bytesCache[key];

    final bytes = await _assetPack.getAssetBytes('images/vocabulary/$key.png');
    _bytesCache[key] = bytes;
    return bytes;
  }

  /// Load image bytes from a full asset pack path (bypassing imageKey
  /// transformation). Used by PackImage.path for phrase/sentence/story
  /// namespaces where the key is already computed upstream.
  Future<Uint8List?> getImageBytesForPath(String packPath) async {
    if (_bytesCache.containsKey(packPath)) return _bytesCache[packPath];

    final bytes = await _assetPack.getAssetBytes(packPath);
    _bytesCache[packPath] = bytes;
    return bytes;
  }

  /// Check if an image exists for the given (awing, english) pair.
  Future<bool> hasImage(String awingWord, String english) async {
    final key = imageKey(awingWord, english);
    if (_bytesCache.containsKey(key)) return _bytesCache[key] != null;

    return await _assetPack.assetExists('images/vocabulary/$key.png');
  }

  /// Check if an image exists at the given asset pack path.
  Future<bool> hasImageAtPath(String packPath) async {
    if (_bytesCache.containsKey(packPath)) return _bytesCache[packPath] != null;

    return await _assetPack.assetExists(packPath);
  }
}
