import 'package:flutter/services.dart';

/// Service for loading vocabulary illustration images.
///
/// Images are generated by scripts/generate_images.py and stored in
/// assets/images/vocabulary/{key}.png where key is the audio key
/// (ASCII-safe version of the Awing word).
class ImageService {
  static final ImageService _instance = ImageService._();
  factory ImageService() => _instance;
  ImageService._();

  /// Cache of which image keys are known to exist (or not).
  final Map<String, bool> _cache = {};

  /// Convert an Awing word to its image asset key.
  /// Matches the same logic as PronunciationService._audioKey().
  static String imageKey(String awingWord) {
    String key = awingWord.toLowerCase();

    // Strip tone diacritics
    key = key
        .replaceAll('á', 'a').replaceAll('à', 'a')
        .replaceAll('â', 'a').replaceAll('ǎ', 'a')
        .replaceAll('é', 'e').replaceAll('è', 'e')
        .replaceAll('ê', 'e').replaceAll('ě', 'e')
        .replaceAll('í', 'i').replaceAll('ì', 'i')
        .replaceAll('î', 'i').replaceAll('ǐ', 'i')
        .replaceAll('ó', 'o').replaceAll('ò', 'o')
        .replaceAll('ô', 'o').replaceAll('ǒ', 'o')
        .replaceAll('ú', 'u').replaceAll('ù', 'u')
        .replaceAll('û', 'u').replaceAll('ǔ', 'u');

    // Replace special vowels with ASCII
    key = key
        .replaceAll('ɛ́', 'e').replaceAll('ɛ̂', 'e').replaceAll('ɛ̌', 'e').replaceAll('ɛ', 'e')
        .replaceAll('ə́', 'e').replaceAll('ə̂', 'e').replaceAll('ə̌', 'e').replaceAll('ə', 'e')
        .replaceAll('ɔ́', 'o').replaceAll('ɔ̂', 'o').replaceAll('ɔ̌', 'o').replaceAll('ɔ', 'o')
        .replaceAll('ɨ́', 'i').replaceAll('ɨ̂', 'i').replaceAll('ɨ̌', 'i').replaceAll('ɨ', 'i')
        .replaceAll('ŋ', 'ng');

    // Remove glottal stops and special characters
    key = key.replaceAll("'", '').replaceAll("\u2019", '').replaceAll("\u2018", '');

    // Remove any remaining non-ASCII characters
    key = key.replaceAll(RegExp(r'[^a-z0-9]'), '');

    return key;
  }

  /// Get the asset path for a vocabulary image.
  static String assetPath(String awingWord) {
    return 'assets/images/vocabulary/${imageKey(awingWord)}.png';
  }

  /// Check if an image asset exists for the given word.
  /// Caches the result for performance.
  Future<bool> hasImage(String awingWord) async {
    final key = imageKey(awingWord);
    if (_cache.containsKey(key)) return _cache[key]!;

    try {
      await rootBundle.load('assets/images/vocabulary/$key.png');
      _cache[key] = true;
      return true;
    } catch (_) {
      _cache[key] = false;
      return false;
    }
  }
}
