import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:awing_ai_learning/services/asset_pack_service.dart';

/// Service for loading vocabulary illustration images from the asset pack.
///
/// Images are generated by scripts/generate_images.py and stored in the
/// install-time asset pack at images/vocabulary/{key}.{ext} where key is
/// the ASCII-safe version of the Awing word and {ext} is `webp` for images
/// generated from v1.24.0 onward, `png` for anything older. Every lookup
/// tries both — see [_imageExtensions].
class ImageService {
  static final ImageService _instance = ImageService._();
  factory ImageService() => _instance;
  /// Static convenience so callers can write `ImageService.instance.x`
  /// without the factory parens. Both forms resolve to the same singleton.
  static ImageService get instance => _instance;
  ImageService._();

  final AssetPackService _assetPack = AssetPackService();

  /// Cache of loaded image bytes.
  final Map<String, Uint8List?> _bytesCache = {};

  /// Set of image keys (filename stems, no extension) confirmed present in
  /// the bundled PAD asset pack. Populated from
  /// `assets/image_manifest.json` by [initialize] at app startup.
  ///
  /// Used by the SYNCHRONOUS [hasImageSync] check so games / quizzes /
  /// exams can filter their vocab selection at round-build time without
  /// awaiting the async PAD-channel `assetExists` round-trip per item.
  ///
  /// Empty set means "manifest not loaded yet OR no images bundled" —
  /// callers must treat the empty case as "don't filter" to avoid
  /// surfacing zero matches when the manifest hasn't loaded.
  final Set<String> _manifestKeys = <String>{};
  bool _manifestLoaded = false;

  /// True once the image manifest JSON has been loaded into [_manifestKeys].
  /// Until this is true, [hasImageSync] returns true for everything (so the
  /// app degrades to "show everything" rather than "show nothing").
  bool get manifestLoaded => _manifestLoaded;
  int get manifestSize => _manifestKeys.length;

  /// Load the image manifest bundled at `assets/image_manifest.json`.
  /// Called once from main() before runApp(). Cheap — the manifest is a
  /// flat list of ~7,000 short strings, total ~200 KB JSON.
  Future<void> initialize() async {
    if (_manifestLoaded) return;
    try {
      final raw = await rootBundle.loadString('assets/image_manifest.json');
      final data = jsonDecode(raw) as Map<String, dynamic>;
      final keys = data['keys'];
      if (keys is List) {
        for (final k in keys) {
          if (k is String && k.isNotEmpty) {
            _manifestKeys.add(k);
          }
        }
      }
      _manifestLoaded = true;
      if (kDebugMode) {
        print('ImageService: loaded ${_manifestKeys.length} image keys '
            'from manifest');
      }
    } catch (e) {
      // Missing manifest is non-fatal — games degrade to "no filtering"
      // and PackImage's existing async fallback (green placeholder) still
      // protects the UI from crashes.
      if (kDebugMode) {
        print('ImageService: image_manifest.json not found ($e) — '
            'sync hasImage checks will return true for all words');
      }
    }
  }

  /// Synchronous "does this image exist in the bundled PAD pack?" check.
  /// Uses the manifest loaded by [initialize]. Returns true if the manifest
  /// hasn't loaded yet (safer default — show all words rather than none).
  ///
  /// Use this in game/quiz/exam vocab filters to avoid surfacing entries
  /// whose illustration tile would render as the green-placeholder fallback.
  bool hasImageSync(String awingWord, String english) {
    if (!_manifestLoaded || _manifestKeys.isEmpty) {
      // Manifest not available — degrade gracefully to "yes, looks ok".
      // PackImage's runtime fallback still covers the actual gap.
      return true;
    }
    return _manifestKeys.contains(imageKey(awingWord, english));
  }

  /// Same as [hasImageSync] but for already-computed image keys (phrases,
  /// sentences, stories where the key is built by a different namespace
  /// function — phraseImageKey etc.).
  bool hasImageKeySync(String key) {
    if (!_manifestLoaded || _manifestKeys.isEmpty) return true;
    return _manifestKeys.contains(key);
  }

  /// Maximum chars of the english slug appended to image filenames.
  /// MUST match `ENGLISH_SLUG_MAX` in scripts/generate_images.py.
  static const int _englishSlugMax = 32;

  /// AUDIO namespace key — one clip per Awing spelling regardless of English
  /// gloss. Used by PronunciationService for MP3 lookups.
  ///
  /// For image lookups, use `imageKey(awing, english)` instead — that key
  /// appends a slug of the english gloss so homonyms ("té" learn vs "té" sit)
  /// and tone-pair collisions each resolve to their own illustration.
  static String audioKey(String awingWord) {
    String key = awingWord.toLowerCase();

    // Strip tone diacritics
    key = key
        .replaceAll('á', 'a').replaceAll('à', 'a')
        .replaceAll('â', 'a').replaceAll('ǎ', 'a')
        .replaceAll('é', 'e').replaceAll('è', 'e')
        .replaceAll('ê', 'e').replaceAll('ě', 'e')
        .replaceAll('í', 'i').replaceAll('ì', 'i')
        .replaceAll('î', 'i').replaceAll('ǐ', 'i')
        .replaceAll('ó', 'o').replaceAll('ò', 'o')
        .replaceAll('ô', 'o').replaceAll('ǒ', 'o')
        .replaceAll('ú', 'u').replaceAll('ù', 'u')
        .replaceAll('û', 'u').replaceAll('ǔ', 'u');

    // Replace special vowels with ASCII
    key = key
        .replaceAll('ɛ́', 'e').replaceAll('ɛ̂', 'e').replaceAll('ɛ̌', 'e').replaceAll('ɛ', 'e')
        .replaceAll('ə́', 'e').replaceAll('ə̂', 'e').replaceAll('ə̌', 'e').replaceAll('ə', 'e')
        .replaceAll('ɔ́', 'o').replaceAll('ɔ̂', 'o').replaceAll('ɔ̌', 'o').replaceAll('ɔ', 'o')
        .replaceAll('ɨ́', 'i').replaceAll('ɨ̂', 'i').replaceAll('ɨ̌', 'i').replaceAll('ɨ', 'i')
        .replaceAll('ŋ', 'ng');

    // Remove glottal stops and special characters
    key = key.replaceAll("'", '').replaceAll("\u2019", '').replaceAll("\u2018", '');

    // Remove any remaining non-ASCII characters
    key = key.replaceAll(RegExp(r'[^a-z0-9]'), '');

    return key;
  }

  /// Slugify an English gloss for use as a filename suffix.
  /// MUST match `english_slug()` in scripts/generate_images.py exactly —
  /// the generator and the app are coupled through this filename format.
  ///
  /// Algorithm: lowercase → strip combining diacritics via NFD → map any
  /// non-[a-z0-9] run to a single underscore → trim edge underscores →
  /// truncate to `_englishSlugMax`. If the gloss is pure punctuation
  /// (slug would be empty), fall back to an MD5-hash prefix so the
  /// filename is still deterministic and unique.
  static String _englishSlug(String english) {
    String s = english.toLowerCase();

    // NFD normalize + strip combining marks (Unicode category Mn).
    // Dart's String doesn't expose Unicode categories directly, so we
    // enumerate the combining marks we actually see in our data (tone
    // diacritics + a safety net via a range check below).
    const combining = [
      '\u0300', '\u0301', '\u0302', '\u0303', '\u0304', '\u0306',
      '\u0307', '\u0308', '\u030a', '\u030b', '\u030c', '\u030f',
      '\u0323', '\u0324', '\u0327', '\u0328',
    ];
    for (final c in combining) {
      s = s.replaceAll(c, '');
    }
    // Belt-and-braces: drop any remaining chars in the U+0300..U+036F
    // combining-mark block.
    final buf = StringBuffer();
    for (final r in s.runes) {
      if (r >= 0x0300 && r <= 0x036F) continue;
      buf.writeCharCode(r);
    }
    s = buf.toString();

    // Anything non-alphanumeric → underscore, collapse runs.
    s = s.replaceAll(RegExp(r'[^a-z0-9]+'), '_');
    // Trim edge underscores.
    s = s.replaceAll(RegExp(r'^_+|_+$'), '');

    if (s.isEmpty) {
      // Pathological: english was all punctuation. Use a stable short hash
      // of the original input. Python uses md5; Dart's `hash` is different
      // so we use the same algorithm intent (first 8 hex chars) but with a
      // simple string hash fallback — the generator should have named the
      // file; the app just needs SOMETHING to look up.
      final code = english.hashCode.abs().toRadixString(16).padLeft(8, '0');
      return code.substring(0, 8);
    }
    if (s.length > _englishSlugMax) {
      s = s.substring(0, _englishSlugMax);
      // Strip trailing underscores created by the truncation boundary.
      s = s.replaceAll(RegExp(r'_+$'), '');
    }
    return s;
  }

  /// Candidate file extensions for a vocabulary illustration, in lookup
  /// order.
  ///
  /// WebP first: v1.24.0 regenerates the library as WebP (quality 82) to
  /// cut ~776 MB of PNG down to roughly a fifth of that. PNGs survive in
  /// two places though — builds made before the regeneration finished, and
  /// community images installed by scripts/apply_contributions.py, which
  /// writes PNG — so every lookup falls back to `.png` instead of
  /// requiring a flag-day migration. Drop `.png` from this list only once
  /// the pack has no PNGs left AND apply_contributions.py writes WebP.
  ///
  /// MUST stay in sync with the extensions accepted by
  /// scripts/build_image_manifest.py, which feeds [_manifestKeys].
  static const List<String> _imageExtensions = <String>['.webp', '.png'];

  /// The extension that last produced a hit, tried first on the next lookup.
  ///
  /// An asset pack is in practice homogeneous — a build ships WebP or it
  /// ships PNG — so without this a PNG-era pack pays a failed `.webp`
  /// platform-channel round-trip for every one of ~9,000 images. With it,
  /// the first lookup costs two calls and the rest cost one. Deliberately
  /// NOT a hard switch: community images from apply_contributions.py are
  /// PNG inside an otherwise-WebP pack, so [_extensionsToTry] still walks
  /// the full list, just in a better order.
  String? _lastHitExtension;

  /// [_imageExtensions] reordered to put [_lastHitExtension] first.
  List<String> get _extensionsToTry {
    final hit = _lastHitExtension;
    if (hit == null || _imageExtensions.first == hit) return _imageExtensions;
    return <String>[hit, ..._imageExtensions.where((e) => e != hit)];
  }

  /// Strip a trailing [_imageExtensions] entry so a pack path collapses to
  /// its extension-less stem. Tolerates paths that already have no
  /// extension, so the pack-path helpers below and any legacy caller still
  /// passing `…/foo.png` both land on the same cache key.
  static String _stem(String packPath) {
    for (final ext in _imageExtensions) {
      if (packPath.endsWith(ext)) {
        return packPath.substring(0, packPath.length - ext.length);
      }
    }
    return packPath;
  }

  /// Image asset key for one (awing, english) pair. Matches the base
  /// filename written by `image_key()` in scripts/generate_images.py.
  ///
  /// NOTE on duplicates: When the Dart source has two identical
  /// (awing, english) literals, the generator writes `{base}.png`,
  /// `{base}__2.png`, `{base}__3.png`, etc. — but this method always
  /// returns the base key, so the app displays the first-occurrence
  /// illustration for every duplicate. See generate_images.py
  /// parse_vocabulary() docstring for the rationale.
  static String imageKey(String awingWord, String english) {
    return '${audioKey(awingWord)}__${_englishSlug(english)}';
  }

  /// Get the asset pack path for a vocabulary image (no "assets/" prefix,
  /// and no file extension — the extension is resolved at load time by
  /// [_imageExtensions], since the same stem may be WebP or PNG).
  static String packPath(String awingWord, String english) {
    return 'images/vocabulary/${imageKey(awingWord, english)}';
  }

  /// Filename-length cap for multi-word keys (matches scripts/generate_images.py
  /// MULTI_WORD_KEY_MAX = 60). Must stay in sync with the Python side.
  static const int _multiWordKeyMax = 60;

  static String _truncate(String key) =>
      key.length > _multiWordKeyMax ? key.substring(0, _multiWordKeyMax) : key;

  /// Image key for an AwingPhrase (greeting, daily, classroom...).
  /// Mirrors `_multi_word_key("phrase", awing)` in generate_images.py.
  ///
  /// These namespaces use the 1-arg audio key (no english gloss suffix)
  /// because each phrase/sentence/story has exactly one canonical text
  /// and doesn't collide with homonyms the way vocabulary words do.
  static String phraseImageKey(String awingPhrase) =>
      'phrase_${_truncate(audioKey(awingPhrase))}';

  /// Image key for an AwingSentence (sentence-building, medium lessons).
  /// Mirrors `_multi_word_key("sentence", awing)` in generate_images.py.
  static String sentenceImageKey(String awingSentence) =>
      'sentence_${_truncate(audioKey(awingSentence))}';

  /// Image key for a StorySentence (stories mode).
  /// Mirrors `_multi_word_key("story", awing)` in generate_images.py.
  static String storyImageKey(String awingSentence) =>
      'story_${_truncate(audioKey(awingSentence))}';

  /// Asset pack paths for the 3 new namespaces. Extension-less, as with
  /// [packPath] — [getImageBytesForPath] picks WebP or PNG.
  static String phrasePackPath(String awingPhrase) =>
      'images/vocabulary/${phraseImageKey(awingPhrase)}';

  static String sentencePackPath(String awingSentence) =>
      'images/vocabulary/${sentenceImageKey(awingSentence)}';

  static String storyPackPath(String awingSentence) =>
      'images/vocabulary/${storyImageKey(awingSentence)}';

  /// Load image bytes from the asset pack. Returns null if not found.
  /// Results are cached for performance.
  ///
  /// Pass the English gloss alongside the Awing word so homonyms resolve
  /// to their own illustrations. Callers that genuinely have no gloss
  /// (legacy code paths) can pass an empty string; the lookup will
  /// degrade to a hash-based slug but WILL MISS the generator-named file.
  Future<Uint8List?> getImageBytes(String awingWord, String english) async {
    return _loadStem(packPath(awingWord, english));
  }

  /// Try each of [_imageExtensions] against [stemPath] and return the first
  /// hit. A miss on every extension is cached as null so a word with no
  /// illustration costs one round-trip per extension, once, rather than on
  /// every rebuild of the widget.
  Future<Uint8List?> _loadStem(String stemPath) async {
    if (_bytesCache.containsKey(stemPath)) return _bytesCache[stemPath];

    Uint8List? bytes;
    for (final ext in _extensionsToTry) {
      bytes = await _assetPack.getAssetBytes('$stemPath$ext');
      if (bytes != null) {
        _lastHitExtension = ext;
        break;
      }
    }
    _bytesCache[stemPath] = bytes;
    return bytes;
  }

  /// Load image bytes from a full asset pack path (bypassing imageKey
  /// transformation). Used by PackImage.path for phrase/sentence/story
  /// namespaces where the key is already computed upstream.
  Future<Uint8List?> getImageBytesForPath(String packPath) async {
    return _loadStem(_stem(packPath));
  }

  /// Check if an image exists for the given (awing, english) pair.
  Future<bool> hasImage(String awingWord, String english) async {
    return _existsStem(packPath(awingWord, english));
  }

  /// Check if an image exists at the given asset pack path. The path's
  /// extension, if it has one, is ignored — WebP and PNG both count.
  Future<bool> hasImageAtPath(String packPath) async {
    return _existsStem(_stem(packPath));
  }

  /// Existence check across [_imageExtensions]. Reuses the bytes cache when
  /// the image has already been loaded, but does NOT populate it — an
  /// existence check should not pull a 100 KB illustration into memory.
  Future<bool> _existsStem(String stemPath) async {
    if (_bytesCache.containsKey(stemPath)) return _bytesCache[stemPath] != null;

    for (final ext in _extensionsToTry) {
      if (await _assetPack.assetExists('$stemPath$ext')) {
        _lastHitExtension = ext;
        return true;
      }
    }
    return false;
  }
}
