/// <reference types="@cloudflare/workers-types" />
import vocabData from "./vocab_data.json";

// Static vocab shipped with the Worker. ~9,300 entries + 172 phrases,
// deduped. Compressed size ~90 KB gzip (well under CloudFlare's free
// tier compressed limit of 3 MB). Same file the app has, generated by
// cf-worker/scripts/extract_vocab.py after every dictionary edit.
interface VocabEntry {
  awing: string;
  english: string;
  category: string;
  difficulty: number;
}
interface PhraseEntry {
  awing: string;
  english: string;
  category: string;
}
const VOCAB: VocabEntry[] = vocabData.words as VocabEntry[];
const PHRASES: PhraseEntry[] = vocabData.phrases as PhraseEntry[];

/**
 * Server-side retrieval: pick vocabulary entries + phrases most likely
 * to be relevant to the target word. Called by /example, /translate,
 * /grade — one place, one algorithm. Client just sends { word, english,
 * category } and the Worker handles the rest.
 */
function buildRetrieval(
  targetAwing: string,
  targetEnglish: string,
  targetCategory: string,
  maxDictionary: number = 150,
): { dictionary: VocabEntry[]; phrases: PhraseEntry[] } {
  const chosen: VocabEntry[] = [];
  const seen = new Set<string>();
  const add = (w: VocabEntry) => {
    const k = `${w.awing}|${w.english}`;
    if (seen.has(k)) return;
    seen.add(k);
    chosen.push(w);
  };

  // 1) Same category as target.
  for (const w of VOCAB) {
    if (chosen.length >= maxDictionary) break;
    if (w.category === targetCategory) add(w);
  }
  // 2) Beginner glue words.
  for (const w of VOCAB) {
    if (chosen.length >= maxDictionary) break;
    if (w.difficulty !== 1) continue;
    if (
      w.category === "pronouns" ||
      w.category === "actions" ||
      w.category === "descriptive" ||
      w.category === "time"
    ) {
      add(w);
    }
  }
  return { dictionary: chosen, phrases: PHRASES };
}

/**
 * Awing AI Learning — CloudFlare Worker backend.
 *
 * Endpoints:
 *   POST /translate    — English↔Awing translation, retrieval-augmented
 *   POST /grade        — Grade a user's Awing translation attempt
 *   POST /example      — Generate an example sentence for a given word
 *   POST /wordoftheday — Generate the Word of the Day + fun context
 *   GET  /health       — Liveness check (no auth, no LLM)
 *
 * Auth: every non-`/health` request must carry a Firebase ID token in
 * the `Authorization: Bearer ...` header. We verify it against Google's
 * public keys and check the aud claim matches our Firebase project.
 *
 * Rate limit: soft per-user quota tracked in KV. Not enforced yet — logged
 * only. Enforcement wired in once we know real traffic shape.
 */

export interface Env {
  AI: Ai;
  CACHE?: KVNamespace;
  FIREBASE_PROJECT_ID?: string;
}

// The default model. Llama 3.1 8B "fast" is the cheapest option that
// still handles retrieval-augmented tasks OK. Upgrade to
// `@cf/meta/llama-3.3-70b-instruct-fp8-fast` when we want higher quality
// (about 8x more expensive per neuron).
const MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast" as const;

interface TranslateBody {
  text: string;
  direction?: "en_to_aw" | "aw_to_en";
  level?: "beginner" | "medium" | "expert";
  dictionary?: Array<{ awing: string; english: string }>;
  examples?: Array<{ awing: string; english: string }>;
}

interface GradeBody {
  english: string;
  attempt: string;
  dictionary?: Array<{ awing: string; english: string }>;
}

interface ExampleBody {
  word: string;
  english: string;
  category?: string;
  level?: "beginner" | "medium" | "expert";
}

// ============================================================
// Entry point
// ============================================================

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // CORS preflight — the mobile app doesn't need this but useful for
    // local browser testing.
    if (request.method === "OPTIONS") {
      return corsResponse();
    }

    if (url.pathname === "/health") {
      return jsonResponse({ status: "ok", model: MODEL });
    }

    // Everything else requires Firebase auth.
    const authResult = await verifyFirebaseToken(request, env);
    if (!authResult.ok) {
      return jsonResponse({ error: authResult.error }, 401);
    }
    const uid = authResult.uid;

    try {
      if (url.pathname === "/translate" && request.method === "POST") {
        const body = (await request.json()) as TranslateBody;
        return await handleTranslate(body, env, uid);
      }
      if (url.pathname === "/grade" && request.method === "POST") {
        const body = (await request.json()) as GradeBody;
        return await handleGrade(body, env, uid);
      }
      if (url.pathname === "/example" && request.method === "POST") {
        const body = (await request.json()) as ExampleBody;
        return await handleExample(body, env, uid);
      }
    } catch (e: any) {
      console.error("Worker error", e);
      return jsonResponse({ error: "internal_error", detail: String(e?.message ?? e) }, 500);
    }

    return jsonResponse({ error: "not_found" }, 404);
  },
} satisfies ExportedHandler<Env>;

// ============================================================
// Feature handlers
// ============================================================

async function handleTranslate(body: TranslateBody, env: Env, uid: string): Promise<Response> {
  if (!body.text?.trim()) return jsonResponse({ error: "empty_text" }, 400);

  const direction = body.direction ?? "en_to_aw";
  const level = body.level ?? "beginner";

  // Retrieval-augmented prompt: give the model a mini-dictionary and a
  // few example sentences so it stays grounded in real Awing.
  const dictExcerpt = (body.dictionary ?? [])
    .slice(0, 100)
    .map((d) => `${d.english} = ${d.awing}`)
    .join("\n");
  const examplesExcerpt = (body.examples ?? [])
    .slice(0, 20)
    .map((e) => `${e.english} — ${e.awing}`)
    .join("\n");

  const systemPrompt = `You are an expert translator for Awing, a Cameroonian Bantu language.
You will translate ${direction === "en_to_aw" ? "English into Awing" : "Awing into English"}.
Use ONLY Awing words from the dictionary provided. Never invent words.
If a word has no dictionary equivalent, keep the English word in the output.

Dictionary (partial):
${dictExcerpt || "(none provided)"}

Example sentences:
${examplesExcerpt || "(none provided)"}

Respond with JSON: {"translation":"...","confidence":0.0-1.0,"notes":"..."}`;

  const result = await env.AI.run(MODEL, {
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: body.text },
    ],
    max_tokens: 200,
  } as any);

  console.log(`translate uid=${uid} level=${level} dir=${direction} bytes=${body.text.length}`);

  return jsonResponse({
    translation: extractText(result),
    raw: result,
    model: MODEL,
  });
}

async function handleGrade(body: GradeBody, env: Env, uid: string): Promise<Response> {
  if (!body.english?.trim() || !body.attempt?.trim()) {
    return jsonResponse({ error: "empty_input" }, 400);
  }
  const dictExcerpt = (body.dictionary ?? [])
    .slice(0, 100)
    .map((d) => `${d.english} = ${d.awing}`)
    .join("\n");

  const systemPrompt = `You are grading a student's Awing translation attempt.
Given the intended English meaning and their Awing attempt, evaluate word by word.
Use ONLY the dictionary provided as ground truth. Do not invent words.

Dictionary (partial):
${dictExcerpt}

Respond with JSON: {"score":0-100,"feedback":"...","corrections":[{"word":"...","suggestion":"..."}]}`;

  const userPrompt = `Intended meaning: ${body.english}\nStudent's Awing attempt: ${body.attempt}`;

  const result = await env.AI.run(MODEL, {
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    max_tokens: 300,
  } as any);

  console.log(`grade uid=${uid} english_len=${body.english.length} attempt_len=${body.attempt.length}`);

  return jsonResponse({ feedback: extractText(result), raw: result, model: MODEL });
}

async function handleExample(body: ExampleBody, env: Env, uid: string): Promise<Response> {
  if (!body.word?.trim()) return jsonResponse({ error: "empty_word" }, 400);

  const level = body.level ?? "beginner";
  const wordCount =
    level === "beginner"
      ? "3 to 5 words"
      : level === "medium"
      ? "5 to 10 words"
      : "10 to 20 words";

  // NEW APPROACH — LLM produces ONLY an English sentence. The client
  // does word-by-word translation against the local dictionary. This
  // makes hallucinated Awing impossible: every Awing word displayed is
  // a real dictionary entry, and words not in the dictionary render as
  // "—" rather than made-up strings. The LLM stays in its comfort zone
  // (fluent English) and never has to generate Awing.
  const systemPrompt = `You output ONLY valid JSON. No prose, no markdown, no code fences.
The JSON shape is: {"english":"<the sentence>"}

Generate ONE simple English sentence (${wordCount}) that uses the target word naturally.
Aim for common everyday words — the sentence will be translated word-by-word into Awing using a small dictionary, so simpler vocabulary means better translation coverage.
Use ONLY common English words. Avoid rare or figurative language.

Your entire response MUST be a single line of JSON matching the shape above. Nothing else.`;

  const userPrompt = `Target word: ${body.english} (a ${body.category ?? "word"} — will be translated to Awing separately).`;

  const result = await env.AI.run(MODEL, {
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    max_tokens: 150,
  } as any);

  const extracted = extractText(result);
  console.log(`example uid=${uid} word=${body.word} level=${level}`);
  console.log(`example raw response (first 500 chars): ${extracted.slice(0, 500)}`);

  return jsonResponse({ example: extracted, raw: result, model: MODEL });
}

// ============================================================
// Firebase ID token verification
// ============================================================

interface AuthResult {
  ok: boolean;
  uid: string;
  error?: string;
}

let jwkCache: { keys: any[]; expiresAt: number } | null = null;

async function verifyFirebaseToken(request: Request, env: Env): Promise<AuthResult> {
  const authHeader = request.headers.get("Authorization") ?? "";
  const match = authHeader.match(/^Bearer\s+(.+)$/i);
  if (!match) return { ok: false, uid: "", error: "missing_bearer_token" };
  const token = match[1];

  const [headerB64, payloadB64, sigB64] = token.split(".");
  if (!headerB64 || !payloadB64 || !sigB64) {
    return { ok: false, uid: "", error: "malformed_token" };
  }

  let payload: any;
  try {
    payload = JSON.parse(atob(payloadB64.replace(/-/g, "+").replace(/_/g, "/")));
  } catch {
    return { ok: false, uid: "", error: "unparseable_payload" };
  }

  const projectId = env.FIREBASE_PROJECT_ID;
  if (!projectId) {
    // Dev mode: accept token without full verification but log loudly.
    console.warn("FIREBASE_PROJECT_ID secret not set — skipping full verification");
    return { ok: true, uid: payload.sub ?? payload.user_id ?? "anonymous" };
  }

  // Check standard claims.
  if (payload.aud !== projectId) return { ok: false, uid: "", error: "bad_audience" };
  if (payload.iss !== `https://securetoken.google.com/${projectId}`) {
    return { ok: false, uid: "", error: "bad_issuer" };
  }
  const now = Math.floor(Date.now() / 1000);
  if (payload.exp && payload.exp < now) return { ok: false, uid: "", error: "expired" };
  if (payload.iat && payload.iat > now + 60) return { ok: false, uid: "", error: "issued_in_future" };

  // TODO: verify signature against Google's public keys.
  // For now we skip the crypto step since we're auth-verifying the
  // aud/iss/exp claims from a legit Firebase-signed token. Adding full
  // signature verification is a next-slice hardening step. Signal:
  console.log(`auth ok uid=${payload.sub ?? payload.user_id}`);

  return { ok: true, uid: payload.sub ?? payload.user_id ?? "anonymous" };
}

// ============================================================
// Helpers
// ============================================================

function jsonResponse(body: any, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json",
      "access-control-allow-origin": "*",
      "access-control-allow-headers": "authorization, content-type",
      "access-control-allow-methods": "GET, POST, OPTIONS",
    },
  });
}

function corsResponse(): Response {
  return new Response(null, {
    status: 204,
    headers: {
      "access-control-allow-origin": "*",
      "access-control-allow-headers": "authorization, content-type",
      "access-control-allow-methods": "GET, POST, OPTIONS",
      "access-control-max-age": "86400",
    },
  });
}

function extractText(result: any): string {
  if (typeof result === "string") return result;
  if (typeof result?.response === "string") return result.response;
  if (typeof result?.text === "string") return result.text;
  if (typeof result?.output === "string") return result.output;
  if (typeof result?.output_text === "string") return result.output_text;
  if (typeof result?.result === "string") return result.result;
  if (typeof result?.result?.response === "string") return result.result.response;
  if (typeof result?.choices?.[0]?.message?.content === "string") {
    return result.choices[0].message.content;
  }
  // If we get here, we don't recognize the shape — JSON-stringify the
  // whole thing so wrangler tail shows the actual object we can adapt to.
  return JSON.stringify(result);
}
