@echo off
REM ============================================================
REM  Cleanup orphan vocabulary PNGs
REM ============================================================
REM  Reads scripts\images_to_delete.txt (generated by Claude)
REM  and deletes each listed PNG from the Play Asset Delivery pack.
REM
REM  Reduces the asset pack size by ~689 MB by removing PNGs
REM  whose Awing word has been removed from the Dart data over
REM  time. SAFE: only deletes files NOT referenced by any current
REM  AwingWord / AwingPhrase / AwingSentence / StorySentence.
REM ============================================================
setlocal

cd /d "%~dp0\.."

if not exist "scripts\images_to_delete.txt" (
  echo ERROR: scripts\images_to_delete.txt not found.
  echo Run the audit first so the list gets regenerated.
  pause
  exit /b 1
)

set "IMG_DIR=android\install_time_assets\src\main\assets\images\vocabulary"
if not exist "%IMG_DIR%" (
  echo ERROR: image directory not found: %IMG_DIR%
  pause
  exit /b 1
)

echo.
echo This will delete every PNG listed in scripts\images_to_delete.txt
echo from %IMG_DIR%.
echo.

for /f %%C in ('find /c /v "" ^< "scripts\images_to_delete.txt"') do set "COUNT=%%C"
echo File count to delete: %COUNT%
echo.

choice /M "Proceed with delete"
if errorlevel 2 (
  echo Aborted.
  exit /b 0
)

echo.
echo Running delete via PowerShell (faster than batch loop for 10k+ files)...

powershell -NoProfile -Command ^
  "$list = Get-Content -LiteralPath '%CD%\scripts\images_to_delete.txt';" ^
  "$imgDir = '%CD%\%IMG_DIR%';" ^
  "$ok = 0; $miss = 0;" ^
  "foreach ($name in $list) {" ^
  "  if ([string]::IsNullOrWhiteSpace($name)) { continue }" ^
  "  $p = Join-Path $imgDir $name;" ^
  "  if (Test-Path -LiteralPath $p) {" ^
  "    Remove-Item -LiteralPath $p -Force -ErrorAction SilentlyContinue;" ^
  "    if (-not (Test-Path -LiteralPath $p)) { $ok++ } else { $miss++ }" ^
  "  } else { $miss++ }" ^
  "  if (($ok %% 500) -eq 0 -and $ok -gt 0) { Write-Host ('  ' + $ok + ' deleted...') }" ^
  "}" ^
  "Write-Host '';" ^
  "Write-Host ('Deleted: ' + $ok);" ^
  "Write-Host ('Missing: ' + $miss);"

if errorlevel 1 (
  echo.
  echo PowerShell step reported an error.
  pause
  exit /b 1
)

echo.
echo Done. Remaining PNGs in the asset pack:
powershell -NoProfile -Command "(Get-ChildItem -LiteralPath '%CD%\%IMG_DIR%' -Filter *.png).Count"

echo.
pause
