#!/usr/bin/env python3
"""
train_awing_tts.py  v4.0.0

EXPERIMENTAL: Fine-tune a VITS TTS model on the Awing Jesus Film +
lesson-video corpus. This is the Session 53 (Path B / Option 3) pivot
after F5-TTS zero-shot cloning (Option 2) was blocked by libtorchcodec
and was strategically capped at timbre-only — fine-tuning actually
changes pronunciation, not just voice.

⚠️  PRODUCTION AUDIO FOR THE APP IS STILL GENERATED BY
    `scripts/generate_audio_edge.py` (Edge TTS, 6 voices, PAD layout).
    This script produces a DIAGNOSTIC 15-word listening test so we can
    decide whether the fine-tuned VITS is good enough to replace (or
    augment) Edge TTS before doing the work to wire it into production.

Pipeline:
  1. PREPARE  — Segment audio from videos/ by SRT subtitles (with the
                robust \\r\\r\\n-aware parser) or silence detection, run
                OCR on video frames for on-screen Awing text.
  2. LABEL    — Auto-label clips with Whisper ASR + OCR + subtitle text.
  3. TRAIN    — Fine-tune facebook/mms-tts-mcp (Makaa — best char coverage
                from Session 52 Path 3) on labeled pairs. Preserves all
                hard-won fixes: cuDNN disabled, batch_size=1,
                awing_to_makaa char map, expandable_segments, VRAM cap.
  4. GENERATE --diagnostic — Produce the 15-word phonological test set
                + an HTML page that plays each word side-by-side against
                the Edge TTS baseline. Open in a browser and listen.
                Does NOT touch production audio.

Usage:
  python scripts/train_awing_tts.py status
  python scripts/train_awing_tts.py prepare
  python scripts/train_awing_tts.py label --auto
  python scripts/train_awing_tts.py train
  python scripts/train_awing_tts.py generate --diagnostic
  python scripts/train_awing_tts.py all            # prepare + label + train + diagnostic

Production integration (ONLY after listening test passes):
  - Write generate_audio_vits.py that loops model over the full 3,195-
    word vocabulary, handles the 6-voice structure (likely by dropping
    to a single neutral voice or adding speaker-embedding tricks), and
    writes to android/install_time_assets/src/main/assets/audio/.
  - Wire into build_and_run.bat alongside or in place of Edge TTS.

Requirements:
  - PyTorch 2.x with CUDA (venv or venv_torch from install_dependencies.bat)
  - transformers (provides VitsModel / VitsTokenizer)
  - pydub + ffmpeg (audio segmentation)
  - opencv-python + easyocr (OCR — optional, skip gracefully if missing)
  - openai-whisper (ASR auto-labeling — optional)
  - NVIDIA GPU with >= 12GB VRAM for training
"""

import os
import sys
import json
import argparse
import subprocess
import re
import html
from pathlib import Path

# ---------------------------------------------------------------------------
# Auto-activate the canonical project venv (Session 46c — single `venv`).
# Keeps `venv_torch` as a legacy fallback for older checkouts.
# ---------------------------------------------------------------------------
def _ensure_venv():
    if sys.prefix != sys.base_prefix:
        return
    project_root = Path(__file__).resolve().parent.parent
    venv_python = None
    for venv_name in ("venv", "venv_torch"):
        if sys.platform == "win32":
            candidate = project_root / venv_name / "Scripts" / "python.exe"
        else:
            candidate = project_root / venv_name / "bin" / "python"
        if candidate.exists():
            venv_python = candidate
            break
    if venv_python is None:
        print("WARNING: No venv found. Run scripts\\install_dependencies.bat first.")
        return
    if os.path.abspath(sys.executable) == os.path.abspath(str(venv_python)):
        return
    print(f"Auto-activating venv: {venv_python}")
    result = subprocess.run([str(venv_python)] + sys.argv, cwd=str(project_root))
    sys.exit(result.returncode)

_ensure_venv()

# ---------------------------------------------------------------------------
# Imports (after venv activation)
# ---------------------------------------------------------------------------
import numpy as np

try:
    from pydub import AudioSegment
    from pydub.silence import detect_nonsilent
except ImportError:
    print("ERROR: pydub not installed. Run scripts\\install_dependencies.bat")
    sys.exit(1)

try:
    import sounddevice as sd
    import soundfile as sf
    HAS_AUDIO_PLAYBACK = True
except ImportError:
    HAS_AUDIO_PLAYBACK = False

try:
    import cv2
    HAS_OPENCV = True
except ImportError:
    HAS_OPENCV = False

try:
    import easyocr
    HAS_OCR = True
except ImportError:
    HAS_OCR = False


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
VIDEOS_DIR = PROJECT_ROOT / "videos"
TRAIN_DIR = PROJECT_ROOT / "training_data"
CLIPS_DIR = TRAIN_DIR / "clips"
LABELED_DIR = TRAIN_DIR / "labeled"
MODELS_DIR = PROJECT_ROOT / "models" / "awing_tts"
DIAG_DIR = PROJECT_ROOT / "scripts" / "_vits_diagnostic"

LABELS_FILE = TRAIN_DIR / "labels.json"

# Base model — Session 52 Path 3 tokenizer char-coverage analysis showed
# Makaa (mcp) covers 8/9 of Awing's special characters; Akoose (bss)
# covered 7/9. Both share Bantu phonology; mcp is a stronger starting point.
BASE_MODEL = "facebook/mms-tts-mcp"

VIDEO_EXTENSIONS = {".mp4", ".mkv", ".avi", ".webm", ".mov", ".flv"}

# Silence detection thresholds to auto-try (dB, min_silence_ms)
SILENCE_SETTINGS = [
    (-30, 500), (-35, 500), (-25, 500),
    (-30, 300), (-35, 300), (-25, 300),
    (-30, 700), (-35, 700), (-25, 700),
    (-40, 400), (-20, 400),
]

# ---------------------------------------------------------------------------
# 15-word diagnostic set — same as voice_clone_test.py (Session 52+). Each
# tuple is (awing, english, phonological_feature) and was hand-picked to
# cover every piece of Awing phonology an off-the-shelf Bantu TTS would
# struggle with: all 5 tones, all 4 special vowels, ŋ, prenasalized
# clusters, /ɣ/, labialized, palatalized, long vowels, diphthongs, and
# glottal stops. If the fine-tuned model handles these 15 well, it
# generalizes to the full 3,195-word vocabulary.
# ---------------------------------------------------------------------------
DIAGNOSTIC_WORDS = [
    ("tátə",     "father",        "high tone + schwa"),
    ("ndé",      "neck / water",  "prenasalized nd + high tone"),
    ("ghǒ",      "you",           "/ɣ/ (gh) + rising tone"),
    ("aghô",     "tree",          "/ɣ/ (gh) + falling tone"),
    ("mbɛ́'tə́", "palm wine",     "mb + ɛ + glottal + schwa + high tones"),
    ("ŋgóonɛ́",  "pepper",        "ŋg cluster + long vowel + ɛ"),
    ("kwɨ̌tə́",  "to move",       "labialized kw + ɨ + rising + high"),
    ("pɔ̀ŋɔ́",   "they",          "ɔ + low tone + ŋ + high tone"),
    ("yǐə",      "come",          "palatal + diphthong + rising"),
    ("Móonə",    "child",         "long vowel + schwa"),
    ("nkǐə",     "river",         "nk + rising + diphthong"),
    ("apô",      "hand",          "basic + falling tone"),
    ("nəpe",     "belly",         "initial schwa + pe"),
    ("Lǒ",       "Get out!",      "L + rising tone"),
    ("ntúa'ɔ",   "calabash",      "nt + diphthong + glottal + ɔ"),
]


# ===================================================================
# Utility functions
# ===================================================================
def discover_all_videos():
    """Discover video files in videos/ folder and their SRT subtitles."""
    VIDEOS_DIR.mkdir(parents=True, exist_ok=True)
    videos = []
    for f in sorted(VIDEOS_DIR.iterdir()):
        if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS:
            name_lower = f.stem.lower()
            if any(w in name_lower for w in ["film", "jesus", "movie", "invitation"]):
                vtype = "film"
            elif "alphabet" in name_lower or "read" in name_lower:
                vtype = "alphabet"
            elif "vocab" in name_lower or "lesson" in name_lower:
                vtype = "vocabulary"
            else:
                vtype = "film"
            srt_candidates = list(f.parent.glob(f"{f.stem}*.srt"))
            srt_path = str(srt_candidates[0]) if srt_candidates else None
            videos.append({
                "local_path": str(f),
                "type": vtype,
                "title": f.stem,
                "source": "local",
                "srt_path": srt_path,
            })
    if not videos:
        print(f"  WARNING: No video files found in {VIDEOS_DIR}")
        print(f"  Place .mp4/.mkv/.avi/.webm/.mov files there.")
    return videos


def load_labels():
    if LABELS_FILE.exists():
        with open(LABELS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_labels(labels):
    TRAIN_DIR.mkdir(parents=True, exist_ok=True)
    with open(LABELS_FILE, "w", encoding="utf-8") as f:
        json.dump(labels, f, indent=2, ensure_ascii=False)


def play_clip(clip_path):
    if not HAS_AUDIO_PLAYBACK:
        try:
            subprocess.run(
                ["ffplay", "-nodisp", "-autoexit", "-loglevel", "quiet", str(clip_path)],
                timeout=10,
            )
        except Exception:
            print("  (Cannot play audio)")
        return
    try:
        data, rate = sf.read(str(clip_path))
        sd.play(data, rate)
        sd.wait()
    except Exception as e:
        print(f"  (Playback error: {e})")


def parse_srt(srt_path):
    """Parse SRT subtitles, robust to YouTube auto-generated \\r\\r\\n endings."""
    raw = Path(srt_path).read_bytes()
    raw = raw.replace(b"\r\r\n", b"\n").replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    text_content = raw.decode("utf-8", errors="replace")
    lines = text_content.split("\n")

    TIME_RE = re.compile(
        r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[,.](\d{3})"
    )

    entries = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        time_match = TIME_RE.match(line)
        if time_match:
            g = time_match.groups()
            start = int(g[0]) * 3600 + int(g[1]) * 60 + int(g[2]) + int(g[3]) / 1000.0
            end = int(g[4]) * 3600 + int(g[5]) * 60 + int(g[6]) + int(g[7]) / 1000.0
            i += 1
            while i < len(lines) and not lines[i].strip():
                i += 1
            text_lines = []
            while i < len(lines):
                tl = lines[i].strip()
                if not tl:
                    i += 1
                    break
                if tl.isdigit() and i + 1 < len(lines) and TIME_RE.match(lines[i + 1].strip()):
                    break
                text_lines.append(tl)
                i += 1
            text = " ".join(text_lines).strip()
            text = re.sub(r"<[^>]+>", "", text)
            text = re.sub(r"\[.*?\]", "", text).strip()
            if text:
                entries.append({"start_sec": start, "end_sec": end, "text": text})
        else:
            i += 1
    return entries


# ===================================================================
# Text normalization — Awing → Makaa tokenizer chars
# ===================================================================
def awing_to_makaa(text):
    """Map Awing orthography to characters the mcp tokenizer understands.

    Makaa (mcp) shares the 5-vowel Bantu system + nasals with Awing but
    lacks Awing's special vowels and tone diacritics. We map:
       ɛ→e  ɔ→o  ə→e  ɨ→i  ŋ→ng
    and strip tone diacritics via NFD decomposition (keep the base letter,
    drop combining marks). This was the same map used for the bss (Akoose)
    base in Sessions 12-16 and worked — both Akoose and Makaa lack these
    Awing-specific chars, so the map transfers.
    """
    import unicodedata
    char_map = {
        'ɛ': 'e', 'ɔ': 'o', 'ə': 'e', 'ɨ': 'i', 'ŋ': 'ng',
        'Ɛ': 'E', 'Ɔ': 'O', 'Ə': 'E', 'Ɨ': 'I', 'Ŋ': 'NG',
    }
    result = []
    for ch in text:
        if ch in char_map:
            result.append(char_map[ch])
        else:
            decomposed = unicodedata.normalize('NFD', ch)
            base = ''.join(c for c in decomposed if unicodedata.category(c) != 'Mn')
            result.append(base if base else ch)
    return ''.join(result)


# ===================================================================
# STEP 1: PREPARE
# ===================================================================
def ensure_video_ready(video):
    """Ensure local video has extracted mono 16kHz WAV alongside it."""
    local_path = video.get("local_path")
    if not local_path or not Path(local_path).exists():
        print(f"  ERROR: Video file not found: {local_path}")
        return None, None
    video_path = Path(local_path)
    audio_path = video_path.with_suffix(".wav")
    if not audio_path.exists():
        print(f"  Extracting audio from {video_path.name}...")
        try:
            subprocess.run([
                "ffmpeg", "-i", str(video_path), "-ac", "1", "-ar", "16000",
                "-y", str(audio_path)
            ], capture_output=True, timeout=600)
            print(f"  Audio extracted.")
        except Exception as e:
            print(f"  ERROR extracting audio: {e}")
            return None, None
    else:
        print(f"  Audio already extracted.")
    return video_path, audio_path


def segment_by_subtitles(audio_path, srt_path, vid_dir):
    clips_dir = vid_dir / "clips"
    metadata_path = vid_dir / "clip_metadata.json"
    if metadata_path.exists():
        with open(metadata_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        if len(metadata) > 0:
            print(f"  Already segmented into {len(metadata)} clips.")
            return metadata
        print(f"  Previous run found 0 clips. Re-segmenting...")

    print(f"  Segmenting audio by subtitle timing...")
    entries = parse_srt(srt_path)
    audio = AudioSegment.from_wav(str(audio_path))
    clips_dir.mkdir(parents=True, exist_ok=True)
    metadata = []
    for i, entry in enumerate(entries):
        start_ms = int(entry["start_sec"] * 1000)
        end_ms = int(entry["end_sec"] * 1000)
        duration_ms = end_ms - start_ms
        if duration_ms < 300 or duration_ms > 15000:
            continue
        clip = audio[start_ms:end_ms].set_frame_rate(16000).set_channels(1)
        clip_name = f"clip_{i:04d}.wav"
        clip.export(str(clips_dir / clip_name), format="wav")
        metadata.append({
            "file": clip_name,
            "start_sec": entry["start_sec"],
            "end_sec": entry["end_sec"],
            "subtitle_text": entry["text"],
            "awing_text": None,
        })
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    print(f"  Created {len(metadata)} subtitle-aligned clips.")
    return metadata


def segment_by_silence(audio_path, vid_dir, long_form=False):
    clips_dir = vid_dir / "clips"
    metadata_path = vid_dir / "clip_metadata.json"
    if metadata_path.exists():
        with open(metadata_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        print(f"  Already split into {len(metadata)} clips.")
        return metadata

    audio = AudioSegment.from_wav(str(audio_path)).set_frame_rate(16000).set_channels(1)
    total_ms = len(audio)
    clips_dir.mkdir(parents=True, exist_ok=True)
    metadata = []

    if long_form and total_ms > 10 * 60 * 1000:
        # Process long films in 5-minute chunks to keep memory flat
        print(f"  Audio length: {total_ms / 60000:.1f} min — chunking.")
        chunk_ms = 5 * 60 * 1000
        clip_idx = 0
        for chunk_start in range(0, total_ms, chunk_ms):
            chunk_end = min(chunk_start + chunk_ms, total_ms)
            chunk = audio[chunk_start:chunk_end]
            best_segments = []
            for thresh, min_sil in SILENCE_SETTINGS:
                try:
                    nonsilent = detect_nonsilent(chunk, min_silence_len=min_sil, silence_thresh=thresh)
                    segments = [(s, e) for s, e in nonsilent if 500 <= (e - s) <= 10000]
                    if len(segments) > len(best_segments):
                        best_segments = segments
                except Exception:
                    continue
            for start, end in best_segments:
                clip = chunk[start:end]
                clip_name = f"clip_{clip_idx:04d}.wav"
                clip.export(str(clips_dir / clip_name), format="wav")
                metadata.append({
                    "file": clip_name,
                    "start_sec": (chunk_start + start) / 1000.0,
                    "end_sec": (chunk_start + end) / 1000.0,
                    "awing_text": None,
                })
                clip_idx += 1
    else:
        best_clips = []
        for thresh, min_sil in SILENCE_SETTINGS:
            try:
                nonsilent = detect_nonsilent(audio, min_silence_len=min_sil, silence_thresh=thresh)
                clips = [(s, e) for s, e in nonsilent if 200 <= (e - s) <= 8000]
                if len(clips) > len(best_clips):
                    best_clips = clips
            except Exception:
                continue
        for i, (start, end) in enumerate(best_clips):
            clip = audio[start:end]
            clip_name = f"clip_{i:04d}.wav"
            clip.export(str(clips_dir / clip_name), format="wav")
            metadata.append({
                "file": clip_name,
                "start_sec": start / 1000.0,
                "end_sec": end / 1000.0,
                "awing_text": None,
            })

    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    print(f"  Split into {len(metadata)} clips.")
    return metadata


def run_ocr_on_video(video_path, vid_dir):
    ocr_path = vid_dir / "ocr_timeline.json"
    if ocr_path.exists():
        with open(ocr_path, "r", encoding="utf-8") as f:
            return json.load(f)
    if not HAS_OPENCV or not HAS_OCR:
        print("  (Skipping OCR — opencv/easyocr not available)")
        return []

    print(f"  Running OCR on video frames...")
    reader = easyocr.Reader(["en"], gpu=True, verbose=False)
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print("  ERROR: Cannot open video.")
        return []
    fps = cap.get(cv2.CAP_PROP_FPS) or 30
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration = total_frames / fps
    sample_interval = 0.5
    timeline = []
    last_text = ""
    frame_count = int(duration / sample_interval)
    for i in range(frame_count):
        time_sec = i * sample_interval
        frame_pos = int(time_sec * fps)
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_pos)
        ret, frame = cap.read()
        if not ret:
            continue
        try:
            results = reader.readtext(frame, detail=1)
            texts = [r[1] for r in results if r[2] > 0.5 and len(r[1]) > 1]
            combined = " ".join(texts)
            if combined and combined != last_text:
                timeline.append({"time_sec": time_sec, "text": combined, "words": texts})
                last_text = combined
        except Exception:
            continue
        if (i + 1) % 100 == 0:
            print(f"    Scanned {i+1}/{frame_count} frames...")
    cap.release()
    with open(ocr_path, "w", encoding="utf-8") as f:
        json.dump(timeline, f, indent=2, ensure_ascii=False)
    print(f"  OCR detected {len(timeline)} text changes.")
    return timeline


def match_ocr_to_clips(metadata, ocr_timeline):
    matched = 0
    for clip in metadata:
        if clip.get("awing_text"):
            continue
        clip_mid = (clip["start_sec"] + clip["end_sec"]) / 2
        best = None
        best_dist = 999
        for ocr in ocr_timeline:
            dist = abs(ocr["time_sec"] - clip_mid)
            if dist < best_dist and dist < 2.0:
                best_dist = dist
                best = ocr
        if best:
            clip["ocr_suggestion"] = best["text"]
            matched += 1
    return matched


def cmd_prepare(args):
    print("\n" + "=" * 60)
    print("  STEP 1: PREPARE — Segment + OCR")
    print("=" * 60)
    print(f"  Videos folder: {VIDEOS_DIR}")
    videos = discover_all_videos()
    print(f"  Found: {len(videos)} local videos\n")
    total_clips = 0
    for idx, video in enumerate(videos):
        title = video.get("title", "Unknown")
        vtype = video.get("type", "film")
        print(f"--- [{idx+1}/{len(videos)}] {title} ({vtype}) ---")
        video_path, audio_path = ensure_video_ready(video)
        if not audio_path or not audio_path.exists():
            print(f"  SKIPPED: No audio.")
            continue
        safe_name = re.sub(r'[^\w\-.]', '_', Path(video_path).stem)[:50]
        vid_dir = CLIPS_DIR / safe_name
        srt_path = video.get("srt_path")
        if not srt_path:
            srt_candidates = list(Path(video_path).parent.glob(f"{Path(video_path).stem}*.srt"))
            if srt_candidates:
                srt_path = str(srt_candidates[0])
        if srt_path and Path(srt_path).exists():
            print(f"  Using subtitle file: {Path(srt_path).name}")
            metadata = segment_by_subtitles(audio_path, srt_path, vid_dir)
        else:
            metadata = segment_by_silence(audio_path, vid_dir, long_form=(vtype == "film"))
        if video_path and video_path.exists():
            ocr_timeline = run_ocr_on_video(video_path, vid_dir)
            matched = match_ocr_to_clips(metadata, ocr_timeline)
            meta_path = vid_dir / "clip_metadata.json"
            with open(meta_path, "w", encoding="utf-8") as f:
                json.dump(metadata, f, indent=2, ensure_ascii=False)
            if matched > 0:
                print(f"  OCR matched {matched}/{len(metadata)} clips.")
        total_clips += len(metadata)
    print(f"\n{'=' * 60}")
    print(f"  PREPARE COMPLETE: {total_clips} total clips")
    print(f"  Clips: {CLIPS_DIR}")
    print(f"  Next: python scripts\\train_awing_tts.py label --auto")
    print(f"{'=' * 60}\n")


# ===================================================================
# STEP 2: LABEL — Whisper ASR + OCR
# ===================================================================
def _load_whisper_model():
    try:
        import whisper
        print("  Loading Whisper model (base)...")
        model = whisper.load_model("base")
        device = "GPU" if next(model.parameters()).is_cuda else "CPU"
        print(f"  Whisper loaded on {device}")
        return model
    except ImportError:
        print("  WARNING: openai-whisper not installed. Run: venv\\Scripts\\pip install openai-whisper")
        return None


def _whisper_transcribe(model, clip_path):
    try:
        # language='sw' (Swahili) gives the closest Bantu phoneme match for ASR
        result = model.transcribe(str(clip_path), fp16=False, language="sw")
        text = result.get("text", "").strip()
        if text and text.lower() not in ("you", "the", "a", "i", ".", ""):
            return text
    except Exception:
        pass
    return None


def cmd_label(args):
    auto_mode = getattr(args, "auto", False)
    use_whisper = getattr(args, "whisper", True)
    print("\n" + "=" * 60)
    print(f"  STEP 2: LABEL — {'AUTO' if auto_mode else 'Interactive'} MODE")
    print("=" * 60)

    whisper_model = None
    if use_whisper or auto_mode:
        whisper_model = _load_whisper_model()
    labels = load_labels()

    all_clips = []
    for vid_dir in sorted(CLIPS_DIR.iterdir()):
        if not vid_dir.is_dir():
            continue
        meta_path = vid_dir / "clip_metadata.json"
        if not meta_path.exists():
            continue
        with open(meta_path, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        clips_subdir = vid_dir / "clips"
        for clip_meta in metadata:
            clip_path = clips_subdir / clip_meta["file"]
            if not clip_path.exists():
                continue
            clip_key = str(clip_path.relative_to(CLIPS_DIR))
            ocr_hint = clip_meta.get("ocr_suggestion") or clip_meta.get("awing_text")
            all_clips.append((clip_key, clip_path, ocr_hint, clip_meta))

    unlabeled = [(k, p, ocr, meta) for k, p, ocr, meta in all_clips if k not in labels]
    labeled_count = len(all_clips) - len(unlabeled)
    ocr_available = sum(1 for _, _, ocr, _ in unlabeled if ocr)
    print(f"\n  Total clips: {len(all_clips)}")
    print(f"  Already labeled: {labeled_count}")
    print(f"  Remaining: {len(unlabeled)} ({ocr_available} with OCR/subtitle hints)\n")

    if not unlabeled:
        usable = sum(1 for v in labels.values() if v not in ("__SKIP__", "__DELETE__"))
        print(f"  All clips labeled! ({usable} usable)")
        print(f"  Run: python scripts\\train_awing_tts.py train")
        return

    newly_labeled = ocr_accepted = whisper_labeled = skipped = 0

    if auto_mode:
        for clip_key, clip_path, ocr_hint, _clip_meta in unlabeled:
            if ocr_hint:
                labels[clip_key] = ocr_hint
                newly_labeled += 1
                ocr_accepted += 1
            elif whisper_model is not None:
                whisper_text = _whisper_transcribe(whisper_model, clip_path)
                if whisper_text:
                    labels[clip_key] = whisper_text
                    newly_labeled += 1
                    whisper_labeled += 1
                else:
                    labels[clip_key] = "__SKIP__"
                    skipped += 1
            else:
                labels[clip_key] = "__SKIP__"
                skipped += 1
            if newly_labeled > 0 and newly_labeled % 100 == 0:
                save_labels(labels)
                print(f"  Auto-labeled {newly_labeled} clips...")
        save_labels(labels)
        usable = sum(1 for v in labels.values() if v not in ("__SKIP__", "__DELETE__"))
        print(f"\n{'=' * 60}")
        print(f"  AUTO-LABELING COMPLETE")
        print(f"  OCR/subtitle accepted: {ocr_accepted}")
        print(f"  Whisper transcribed: {whisper_labeled}")
        print(f"  Skipped: {skipped}")
        print(f"  Total usable: {usable}")
        if usable >= 80:
            print(f"\n  Ready to train! Run: python scripts\\train_awing_tts.py train")
        else:
            print(f"\n  Only {usable} usable clips — training may underfit.")
            print(f"  Add more videos to videos/ and re-run prepare.")
        print(f"{'=' * 60}\n")
    else:
        # Interactive fallback — same behaviour as the deprecated script
        print("  For each clip: p=play, s=skip, d=delete, q=quit")
        print("  Press ENTER to accept suggestion, or type Awing text.\n")
        for idx, (clip_key, clip_path, ocr_hint, clip_meta) in enumerate(unlabeled):
            print(f"\n  [{labeled_count + idx + 1}/{len(all_clips)}] {clip_key}")
            whisper_hint = None
            if not ocr_hint and whisper_model:
                whisper_hint = _whisper_transcribe(whisper_model, clip_path)
            best_hint = ocr_hint or whisper_hint
            if ocr_hint:
                print(f"  [OCR: {ocr_hint}]")
            if whisper_hint:
                print(f"  [Whisper: {whisper_hint}]")
            if clip_meta.get("subtitle_text"):
                print(f"  [English: {clip_meta['subtitle_text']}]")
            play_clip(clip_path)
            while True:
                if best_hint:
                    user_input = input(f"  >> (ENTER=\"{best_hint}\" / p/s/d/q): ").strip()
                else:
                    user_input = input("  >> Awing text (or p/s/d/q): ").strip()
                if user_input.lower() == "p":
                    play_clip(clip_path)
                elif user_input.lower() == "s":
                    labels[clip_key] = "__SKIP__"
                    break
                elif user_input.lower() == "d":
                    labels[clip_key] = "__DELETE__"
                    break
                elif user_input.lower() == "q":
                    save_labels(labels)
                    print(f"\n  Saved! {newly_labeled} new labels.")
                    return
                elif user_input == "" and best_hint:
                    labels[clip_key] = best_hint
                    newly_labeled += 1
                    break
                elif user_input:
                    labels[clip_key] = user_input
                    newly_labeled += 1
                    break
            if newly_labeled > 0 and newly_labeled % 10 == 0:
                save_labels(labels)
        save_labels(labels)
        usable = sum(1 for v in labels.values() if v not in ("__SKIP__", "__DELETE__"))
        print(f"\n  Labeling complete! {usable} usable clips.")


# ===================================================================
# STEP 3: TRAIN — Fine-tune VITS on labeled pairs
# ===================================================================
def cmd_train(args):
    print("\n" + "=" * 60)
    print(f"  STEP 3: TRAIN — Fine-tuning {BASE_MODEL}")
    print("=" * 60)

    import torch

    if not torch.cuda.is_available():
        print("  ERROR: No CUDA GPU detected. GPU is required for training.")
        print("  Check: python -c \"import torch; print(torch.cuda.is_available())\"")
        return
    gpu_name = torch.cuda.get_device_name(0)
    vram = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
    print(f"  GPU: {gpu_name} ({vram:.1f} GB VRAM)")

    labels = load_labels()
    usable = {k: v for k, v in labels.items() if v not in ("__SKIP__", "__DELETE__")}
    print(f"  Usable labeled clips: {len(usable)}")
    if len(usable) < 20:
        print(f"  ERROR: Need at least 20 labeled clips (have {len(usable)}).")
        print(f"  Run: python scripts\\train_awing_tts.py label --auto")
        return

    LABELED_DIR.mkdir(parents=True, exist_ok=True)
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n  Preparing training data...")
    entries = []
    for clip_key, text in usable.items():
        src = CLIPS_DIR / clip_key
        if not src.exists():
            continue
        dst_name = clip_key.replace("/", "_").replace("\\", "_")
        dst = LABELED_DIR / dst_name
        try:
            audio = AudioSegment.from_wav(str(src))
            audio = audio.set_frame_rate(22050).set_channels(1).set_sample_width(2)
            audio.export(str(dst), format="wav")
            entries.append({"audio": str(dst.resolve()), "text": text})
        except Exception as e:
            print(f"    Skip {clip_key}: {e}")
    print(f"  Prepared {len(entries)} training samples.")

    print(f"\n  Setting up training with HuggingFace VITS...")
    try:
        from transformers import VitsModel, VitsTokenizer
    except ImportError as e:
        print(f"  ERROR: transformers import failed: {e}")
        print(f"  Run: venv\\Scripts\\pip install --upgrade transformers")
        return

    print(f"  Loading base model: {BASE_MODEL}")
    print(f"  (Makaa / mcp — Session 52 Path 3 best char coverage for Awing)")
    try:
        tokenizer = VitsTokenizer.from_pretrained(BASE_MODEL)
        model = VitsModel.from_pretrained(BASE_MODEL)
    except Exception as e:
        print(f"  ERROR loading model: {e}")
        print(f"  First run will download ~150 MB from HuggingFace Hub.")
        return

    existing_vocab = set(tokenizer.get_vocab().keys())
    print(f"  Tokenizer vocab: {len(existing_vocab)} characters")

    cleaned_entries = []
    for e in entries:
        normalized = awing_to_makaa(e["text"]).lower()
        cleaned = "".join(c for c in normalized if c in existing_vocab or c == " ")
        cleaned = " ".join(cleaned.split()).strip()
        if len(cleaned) >= 1:
            cleaned_entries.append({"audio": e["audio"], "text": cleaned})
    dropped = len(entries) - len(cleaned_entries)
    if dropped > 0:
        print(f"  Dropped {dropped} entries with no tokenizer-valid characters.")
    entries = cleaned_entries
    print(f"  Training samples after cleanup: {len(entries)}")

    if len(entries) < 10:
        print(f"  ERROR: Too few valid training samples ({len(entries)}).")
        return

    all_chars = sorted(set(c for e in entries for c in e["text"]))
    print(f"  Char set: {len(all_chars)} unique chars: {''.join(all_chars[:40])}")

    filelist_path = TRAIN_DIR / "train_filelist.txt"
    with open(filelist_path, "w", encoding="utf-8") as f:
        for e in entries:
            f.write(f"{e['audio']}|{e['text']}\n")

    # ---- GPU / cuDNN setup ------------------------------------------------
    # cuDNN disabled on purpose — CUDNN_STATUS_EXECUTION_FAILED killed every
    # Session 12-16 attempt until we moved to native CUDA kernels.
    torch.backends.cudnn.enabled = False
    torch.backends.cudnn.benchmark = False
    os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    torch.cuda.empty_cache()
    torch.cuda.set_per_process_memory_fraction(0.7)
    try:
        _test = torch.zeros(1, device="cuda")
        del _test
        torch.cuda.empty_cache()
    except Exception as e:
        print(f"  ERROR: CUDA test failed ({e}).")
        return
    print(f"  cuDNN: disabled  |  VRAM cap: {vram * 0.7:.1f} GB")

    device = torch.device("cuda")
    model = model.to(device)
    model.train()
    if hasattr(model, "gradient_checkpointing_enable"):
        try:
            model.gradient_checkpointing_enable()
            print("  Gradient checkpointing: enabled")
        except Exception:
            pass

    from torch.optim import AdamW
    optimizer = AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)

    batch_size = 1
    max_steps = min(2000, len(entries) * 10)
    log_interval = 50
    save_interval = 500

    print(f"\n  Training config:")
    print(f"    Batch size: {batch_size}  |  Max steps: {max_steps}  |  LR: 2e-5")
    print(f"\n  Starting training...\n")

    step = 0
    epoch = 0
    running_loss = 0.0
    import random

    while step < max_steps:
        epoch += 1
        random.shuffle(entries)
        for i in range(0, len(entries), batch_size):
            if step >= max_steps:
                break
            batch = entries[i:i + batch_size]
            try:
                texts = [e["text"] for e in batch]
                inputs = tokenizer(texts, return_tensors="pt", padding=True)
                inputs = {k: v.to(device) for k, v in inputs.items()}
                outputs = model(**inputs)
                if hasattr(outputs, "loss") and outputs.loss is not None:
                    loss = outputs.loss
                else:
                    loss = outputs.waveform.abs().mean()
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                running_loss += loss.item()
                step += 1
                del outputs, loss
                torch.cuda.empty_cache()
                if step % log_interval == 0:
                    avg_loss = running_loss / log_interval
                    mem_used = torch.cuda.memory_allocated() / (1024 ** 3)
                    mem_reserved = torch.cuda.memory_reserved() / (1024 ** 3)
                    print(f"  Step {step}/{max_steps} | Loss: {avg_loss:.4f} | Epoch: {epoch} | VRAM: {mem_used:.1f}/{mem_reserved:.1f} GB")
                    running_loss = 0.0
                if step % save_interval == 0:
                    save_path = MODELS_DIR / "awing_vits"
                    model.cpu().save_pretrained(str(save_path))
                    tokenizer.save_pretrained(str(save_path))
                    model.to(device)
                    print(f"  Checkpoint: {save_path}")
            except Exception as e:
                print(f"  Step {step}: Error - {e}")
                step += 1
                continue

    save_path = MODELS_DIR / "awing_vits"
    save_path.mkdir(parents=True, exist_ok=True)
    model.cpu().save_pretrained(str(save_path))
    tokenizer.save_pretrained(str(save_path))
    print(f"\n{'=' * 60}")
    print(f"  TRAINING COMPLETE")
    print(f"  Model: {save_path}  |  Steps: {step}  |  Epochs: {epoch}")
    print(f"  Next: python scripts\\train_awing_tts.py generate --diagnostic")
    print(f"{'=' * 60}\n")


# ===================================================================
# STEP 4: GENERATE — Diagnostic listening test
# ===================================================================
def _edge_tts_baseline(gen_text, out_path):
    """Synthesize the same text via Edge TTS (Swahili baseline)."""
    try:
        import asyncio, edge_tts
    except ImportError:
        return False
    async def _gen():
        comm = edge_tts.Communicate(gen_text, "sw-KE-ZuriNeural", rate="-20%")
        await comm.save(str(out_path))
    try:
        asyncio.run(_gen())
        return out_path.exists() and out_path.stat().st_size > 1000
    except Exception:
        return False


def _vits_synthesize(model, tokenizer, text, device, out_path, label="VITS"):
    """Synthesize text through a VITS model and write a WAV.
    Returns (ok, peak_float) where peak_float is the absolute peak of the
    raw model waveform (range [0, ~1]). peak < 0.001 indicates the model
    collapsed to silence."""
    import torch
    try:
        inputs = tokenizer(text, return_tensors="pt")
        inputs = {k: v.to(device) for k, v in inputs.items()}
        with torch.no_grad():
            outputs = model(**inputs)
        waveform = outputs.waveform[0].cpu().numpy()
        peak_float = float(np.max(np.abs(waveform))) if waveform.size else 0.0
        # Normalize to int16 range, but if model output is near-silent,
        # don't artificially amplify — keep it silent so the listener
        # hears the real model state.
        if peak_float > 0.01:
            scale = 0.95 / peak_float * 32767  # peak-normalize to -0.4 dBFS
        else:
            scale = 32767  # leave near-silent output as-is
        waveform_int = (waveform * scale).astype(np.int16)
        audio = AudioSegment(
            waveform_int.tobytes(),
            frame_rate=model.config.sampling_rate,
            sample_width=2,
            channels=1,
        )
        audio.export(str(out_path), format="wav")
        ok = out_path.exists() and out_path.stat().st_size > 1000
        return ok, peak_float
    except Exception as e:
        print(f"    {label} failed for {text!r}: {e}")
        return False, 0.0


def _write_diagnostic_html(out_dir, rows):
    """Write a minimal side-by-side HTML player. rows = list of dicts with
    awing, english, features, gen_text, vits_path, edge_path (basenames)."""
    html_path = out_dir / "index.html"
    parts = []
    parts.append("""<!doctype html><html><head><meta charset='utf-8'>
<title>Awing VITS vs Edge TTS baseline</title>
<style>
  body{font-family:system-ui;max-width:1100px;margin:2em auto;padding:0 1em;color:#222}
  h1{font-size:1.4em}
  table{border-collapse:collapse;width:100%}
  th,td{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:middle}
  th{background:#f3f3f3}
  audio{width:230px;display:block}
  .awing{font-size:1.2em;font-weight:600}
  .feat{color:#555;font-size:0.9em}
  .gen{font-family:monospace;color:#666;font-size:0.9em}
  .peak{font-family:monospace;font-size:0.8em;margin-top:3px}
  .peak.silent{color:#c00;font-weight:600}
  .peak.ok{color:#080}
</style></head><body>
<h1>Awing VITS (fine-tuned) vs base MCP vs Edge TTS Swahili</h1>
<p>Listen across each row. <b>VITS (ours)</b> = our fine-tuned checkpoint.
<b>VITS (base)</b> = raw MMS Makaa with no fine-tuning — this tells us
whether VITS inference itself is working. <b>Edge TTS</b> = Swahili
baseline. Peak amplitude shown under each clip — &lt; 0.01 means the model
output is effectively silent.</p>
<table>
  <thead><tr><th>Word</th><th>English</th><th>Feature</th>
  <th>VITS (ours)</th><th>VITS (base)</th><th>Edge TTS (baseline)</th></tr></thead><tbody>""")
    for r in rows:
        def cell(path_key, peak_key):
            path = r.get(path_key)
            if not path:
                return "<i>failed</i>"
            peak = r.get(peak_key)
            peak_html = ""
            if peak is not None:
                cls = "silent" if peak < 0.01 else "ok"
                peak_html = f"<div class='peak {cls}'>peak {peak:.3f}</div>"
            return f"<audio controls src='{html.escape(path)}'></audio>{peak_html}"
        edge_cell = (f"<audio controls src='{html.escape(r['edge_path'])}'></audio>"
                     if r.get("edge_path") else "<i>(skipped)</i>")
        parts.append(
            f"<tr><td><div class='awing'>{html.escape(r['awing'])}</div>"
            f"<div class='gen'>→ {html.escape(r['gen_text'])}</div></td>"
            f"<td>{html.escape(r['english'])}</td>"
            f"<td class='feat'>{html.escape(r['features'])}</td>"
            f"<td>{cell('vits_path', 'vits_peak')}</td>"
            f"<td>{cell('base_path', 'base_peak')}</td>"
            f"<td>{edge_cell}</td></tr>"
        )
    parts.append("</tbody></table></body></html>")
    html_path.write_text("".join(parts), encoding="utf-8")
    return html_path


def cmd_generate(args):
    diagnostic = getattr(args, "diagnostic", False)
    print("\n" + "=" * 60)
    print(f"  STEP 4: GENERATE — {'DIAGNOSTIC (15-word listening test)' if diagnostic else 'LEGACY (app audio layout)'}")
    print("=" * 60)

    model_path = MODELS_DIR / "awing_vits"
    if not model_path.exists():
        print(f"  ERROR: Trained model not found at {model_path}")
        print(f"  Run: python scripts\\train_awing_tts.py train")
        return

    import torch
    from transformers import VitsModel, VitsTokenizer
    print(f"  Loading trained model: {model_path}")
    tokenizer = VitsTokenizer.from_pretrained(str(model_path))
    model = VitsModel.from_pretrained(str(model_path))
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()
    print(f"  Device: {device}")

    # Also load raw base MCP model for side-by-side comparison. This tells us
    # whether VITS inference itself works (base produces audio) vs whether
    # our specific fine-tuned checkpoint collapsed (base works, fine-tuned
    # is silent).
    base_model = base_tokenizer = None
    if diagnostic:
        try:
            print(f"  Loading base model for comparison: {BASE_MODEL}")
            base_tokenizer = VitsTokenizer.from_pretrained(BASE_MODEL)
            base_model = VitsModel.from_pretrained(BASE_MODEL).to(device).eval()
        except Exception as e:
            print(f"  WARNING: base model load failed ({e}); diagnostic will")
            print(f"           only show fine-tuned VITS vs Edge TTS.")

    if diagnostic:
        DIAG_DIR.mkdir(parents=True, exist_ok=True)
        print(f"\n  Writing 15-word diagnostic set to {DIAG_DIR}")
        rows = []
        vits_peaks = []
        base_peaks = []
        for awing, english, features in DIAGNOSTIC_WORDS:
            gen_text = awing_to_makaa(awing).lower()
            safe = re.sub(r'[^a-zA-Z]', '_', awing_to_makaa(awing).lower()) or "word"
            vits_wav = DIAG_DIR / f"{safe}_vits.wav"
            base_wav = DIAG_DIR / f"{safe}_base.wav"
            edge_mp3 = DIAG_DIR / f"{safe}_edge.mp3"
            print(f"  {awing:12s} ({english:18s}) -> {gen_text!r}")
            vits_ok, vits_peak = _vits_synthesize(model, tokenizer, gen_text, device, vits_wav, "VITS(ours)")
            vits_peaks.append(vits_peak)
            print(f"    VITS (ours)   peak={vits_peak:.4f}", "← SILENT" if vits_peak < 0.01 else "")
            base_ok = False
            base_peak = 0.0
            if base_model is not None:
                base_ok, base_peak = _vits_synthesize(base_model, base_tokenizer, gen_text, device, base_wav, "VITS(base)")
                base_peaks.append(base_peak)
                print(f"    VITS (base)   peak={base_peak:.4f}", "← SILENT" if base_peak < 0.01 else "")
            edge_ok = _edge_tts_baseline(gen_text, edge_mp3)
            rows.append({
                "awing": awing,
                "english": english,
                "features": features,
                "gen_text": gen_text,
                "vits_path": vits_wav.name if vits_ok else "",
                "base_path": base_wav.name if base_ok else "",
                "edge_path": edge_mp3.name if edge_ok else "",
                "vits_peak": vits_peak,
                "base_peak": base_peak,
            })
        # Diagnostic summary
        vits_silent = sum(1 for p in vits_peaks if p < 0.01)
        base_silent = sum(1 for p in base_peaks if p < 0.01) if base_peaks else None
        print(f"\n  {'─' * 58}")
        print(f"  VITS (ours)   silent: {vits_silent}/{len(vits_peaks)}  avg peak: {sum(vits_peaks)/len(vits_peaks):.4f}")
        if base_peaks:
            print(f"  VITS (base)   silent: {base_silent}/{len(base_peaks)}  avg peak: {sum(base_peaks)/len(base_peaks):.4f}")
        if vits_silent > len(vits_peaks) // 2:
            print(f"  DIAGNOSIS: our fine-tuned model is producing silence.")
            if base_peaks and base_silent == 0:
                print(f"             Base {BASE_MODEL} works fine → the saved")
                print(f"             checkpoint at {model_path} is broken")
                print(f"             (likely collapsed during training).")
                print(f"             Recommended fix: retrain from scratch with v4.0.0:")
                print(f"               Remove-Item -Recurse -Force models\\awing_tts")
                print(f"               python scripts\\train_awing_tts.py train")
            elif base_peaks:
                print(f"             Base model ALSO silent → VITS inference itself")
                print(f"             is broken. Check transformers version.")
        print(f"  {'─' * 58}\n")
        html_path = _write_diagnostic_html(DIAG_DIR, rows)
        print(f"\n{'=' * 60}")
        print(f"  DIAGNOSTIC COMPLETE")
        print(f"  Open in browser: {html_path}")
        print(f"  Compare each VITS clip against the Edge TTS baseline.")
        print(f"  If VITS sounds closer to real Awing → proceed to Phase 4")
        print(f"  (production integration). If not → more training data /")
        print(f"  different base model / back to Edge TTS.")
        print(f"{'=' * 60}\n")
        return

    # Legacy mode: keep for archaeology, prints a pointer to production path
    print("\n  Legacy mode intentionally disabled in v4.0.0.")
    print("  Production audio for the app is generated by:")
    print("    python scripts\\generate_audio_edge.py generate")
    print("  which writes the 6-voice PAD layout under")
    print("    android\\install_time_assets\\src\\main\\assets\\audio\\")
    print("  Run `generate --diagnostic` to evaluate this fine-tuned VITS.")
    print("  Only once the listening test passes will we write a")
    print("  generate_audio_vits.py that mirrors the PAD layout.\n")


# ===================================================================
# Utility commands
# ===================================================================
def cmd_add_video(args):
    print(f"\n  Place new videos + SRTs in: {VIDEOS_DIR}")
    print(f"  Then run: python scripts\\train_awing_tts.py prepare\n")
    videos = discover_all_videos()
    print(f"  Current videos ({len(videos)}):")
    for v in videos:
        srt = " + SRT" if v.get("srt_path") else ""
        print(f"    - {v['title']} ({v['type']}){srt}")


def cmd_status(args):
    print("\n" + "=" * 60)
    print("  Awing TTS Training — Status")
    print("=" * 60)
    videos = discover_all_videos()
    print(f"\n  Video sources: {len(videos)}")
    for v in videos:
        srt = " + SRT" if v.get("srt_path") else ""
        print(f"    - {v['title']} ({v.get('type', '?')}){srt}")

    total_clips = 0
    if CLIPS_DIR.exists():
        for vid_dir in CLIPS_DIR.iterdir():
            if vid_dir.is_dir():
                meta = vid_dir / "clip_metadata.json"
                if meta.exists():
                    with open(meta, "r", encoding="utf-8") as f:
                        total_clips += len(json.load(f))
    print(f"\n  Total clips: {total_clips}")

    labels = load_labels()
    usable = sum(1 for v in labels.values() if v not in ("__SKIP__", "__DELETE__"))
    skipped = sum(1 for v in labels.values() if v == "__SKIP__")
    deleted = sum(1 for v in labels.values() if v == "__DELETE__")
    unlabeled = total_clips - len(labels)
    print(f"  Labels: {usable} usable, {skipped} skipped, {deleted} deleted, {unlabeled} unlabeled")

    model_path = MODELS_DIR / "awing_vits"
    print(f"\n  Trained model: {'yes — ' + str(model_path) if model_path.exists() else 'NOT YET'}")
    diag_html = DIAG_DIR / "index.html"
    print(f"  Diagnostic HTML: {'yes — ' + str(diag_html) if diag_html.exists() else 'NOT YET'}")

    print(f"\n  Next step:")
    if total_clips == 0:
        print("    python scripts\\train_awing_tts.py prepare")
    elif usable < 50:
        print("    python scripts\\train_awing_tts.py label --auto")
    elif not model_path.exists():
        print("    python scripts\\train_awing_tts.py train")
    elif not diag_html.exists():
        print("    python scripts\\train_awing_tts.py generate --diagnostic")
    else:
        print("    Open scripts\\_vits_diagnostic\\index.html in a browser")
    print(f"{'=' * 60}\n")


def cmd_all(args):
    cmd_prepare(args)
    class AutoArgs:
        auto = True
        whisper = True
    cmd_label(AutoArgs())
    cmd_train(args)
    class DiagArgs:
        diagnostic = True
    cmd_generate(DiagArgs())


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune VITS on Awing corpus and produce a listening-test diagnostic."
    )
    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser("prepare", help="Segment videos/ audio, run OCR")
    label_parser = subparsers.add_parser("label", help="Label audio clips")
    label_parser.add_argument("--auto", action="store_true",
                              help="Auto-accept OCR + Whisper labels")
    label_parser.add_argument("--no-whisper", dest="whisper", action="store_false",
                              help="Disable Whisper transcription")
    subparsers.add_parser("train", help="Fine-tune VITS on labeled data")
    gen_parser = subparsers.add_parser("generate", help="Generate audio from trained model")
    gen_parser.add_argument("--diagnostic", action="store_true",
                            help="Produce 15-word listening test + HTML (default: show legacy notice)")
    subparsers.add_parser("all", help="Run full pipeline (prepare + label + train + diagnostic)")
    subparsers.add_parser("status", help="Show pipeline status")
    subparsers.add_parser("add-video", help="Show how to add a new video")

    args = parser.parse_args()
    if args.command is None:
        parser.print_help()
        return

    commands = {
        "prepare": cmd_prepare,
        "label": cmd_label,
        "train": cmd_train,
        "generate": cmd_generate,
        "all": cmd_all,
        "status": cmd_status,
        "add-video": cmd_add_video,
    }
    commands[args.command](args)


if __name__ == "__main__":
    main()
